/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.fundacionjala.trello.unit;

import org.fundacionjala.trello.App;
import org.testng.annotations.Test;

import static org.testng.Assert.assertNotNull;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
